DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS users
(
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name  VARCHAR NOT NULL,
   email VARCHAR NOT NULL,
   CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
   id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name         VARCHAR NOT NULL,
   description  VARCHAR NOT NULL,
   is_available BOOLEAN NOT NULL,
   owner_id     BIGINT  NOT NULL,
   request_id   BIGINT  NOT NULL,
   FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
   id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   item_id    BIGINT                      NOT NULL,
   booker_id  BIGINT                      NOT NUll,
   status     VARCHAR                     NOT NULL,
   FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
   FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   text        VARCHAR                     NOT NULl,
   item_id     BIGINT                      NOT NUll,
   author_id   BIGINT                      NOT NULl,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
   FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR NOT NULL,
    requestor_id BIGINT  NOT NULL,
    FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);
